site_name: Fit
docs_dir: doc/src
site_dir: doc/html/
repo_url: https://github.com/pfultz2/Fit
use_directory_urls: false
pages:
- ['index.md', 'Home']
- ['overview.md', 'User Guide', 'Overview']
# Adaptors
- ['compose.md', 'Adaptors', 'compose']
- ['conditional.md', 'Adaptors', 'conditional']
- ['fix.md', 'Adaptors', 'fix']
- ['fuse.md', 'Adaptors', 'fuse']
- ['implicit.md', 'Adaptors', 'implicit']
- ['indirect.md', 'Adaptors', 'indirect']
- ['invoke.md', 'Adaptors', 'invoke']
- ['lazy.md', 'Adaptors', 'lazy']
- ['match.md', 'Adaptors', 'match']
- ['mutable.md', 'Adaptors', 'mutable']
- ['on.md', 'Adaptors', 'on']
- ['partial.md', 'Adaptors', 'partial']
- ['pipable.md', 'Adaptors', 'pipable']
- ['placeholders.md', 'Adaptors', 'placeholders']
- ['protect.md', 'Adaptors', 'protect']
- ['reveal.md', 'Adaptors', 'reveal']
- ['static.md', 'Adaptors', 'static']
- ['variadic.md', 'Adaptors', 'variadic']
# Functions
- ['always.md', 'Functions', 'always']
- ['identity.md', 'Functions', 'identity']
# Utilities
- ['args.md', 'Utilities', 'args']
- ['is_callable.md', 'Utilities', 'is_callable']
- ['lambda.md', 'Utilities', 'FIT_STATIC_LAMBDA']
- ['returns.md', 'Utilities', 'returns']
- ['returns.md', 'Utilities', 'tap']
